const catProfiles = [
  {
    name: '奶霜',
    status: '在校',
    friendliness: '行踪不定，难抓',
    vaccine: '一针 2026-04-29；二针未接种；三针未接种',
    nextWindow: '第二针超窗口，需咨询医生',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '原第二针窗口 5.20~5.27；因抓不到暂未接种，抓到后咨询医生补种方案。',
    source: '在校猫咪名单'
  },
  {
    name: '水手',
    status: '在校',
    friendliness: '不怕人',
    vaccine: '一针 2026-05-10；二针 2026-05-31；三针未接种',
    nextWindow: '第三针 6.21~6.28',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第三针认捐人：蔚蓝future',
    source: '在校猫咪名单'
  },
  {
    name: '虎先锋',
    status: '在校',
    friendliness: '有点怕人，需上笼子',
    vaccine: '一针 2026-05-11；二针未接种；三针未接种',
    nextWindow: '第二针 6.1~6.8',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '警长',
    status: '在校',
    friendliness: '行踪不定',
    vaccine: '一针 2025-11-01；二针未接种；三针未接种',
    nextWindow: '第二针超窗口，需咨询医生',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '银杏',
    status: '在校',
    friendliness: '状态待补充',
    vaccine: '一针 2025-11-30；二针未接种；三针未接种',
    nextWindow: '第二针超窗口，需咨询医生',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第二/三针认捐人：毛橘妈',
    source: '在校猫咪名单'
  },
  {
    name: '黑小虎',
    status: '在校',
    friendliness: '行踪不定，状态待补充',
    vaccine: '一针 2025-11-30；二针未接种；三针未接种',
    nextWindow: '第二针超窗口，需咨询医生',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第二/三针认捐人：长乐',
    source: '在校猫咪名单'
  },
  {
    name: '茶叶大蛋',
    status: '在校',
    friendliness: '有点怕人，需上笼子',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第二/三针认捐人：毛橘妈',
    source: '在校猫咪名单'
  },
  {
    name: '黑哥',
    status: '在校',
    friendliness: '行踪不定，状态待补充',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第二针认捐人：鲨人不wink',
    source: '在校猫咪名单'
  },
  {
    name: '斜眼狼儿子（彪哥）',
    status: '在校',
    friendliness: '有点怕人，需上笼子',
    vaccine: '一针 2026-05-20；二针未接种；三针未接种',
    nextWindow: '第二针 6.10~6.17',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第二针认捐人：鲨人不wink',
    source: '在校猫咪名单'
  },
  {
    name: '豆介',
    status: '在校',
    friendliness: '有点怕人，需上笼子',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第二针认捐人：刘岛；第三针认捐人：李介清',
    source: '在校猫咪名单'
  },
  {
    name: '大面包',
    status: '在校',
    friendliness: '不怕人',
    vaccine: '一针 2025-08-01；二针 2025-09-01；三针 2026-04-29',
    nextWindow: '加强针 2027-03-24',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '第三针由大面包car协助',
    source: '在校猫咪名单'
  },
  {
    name: '芸豆',
    status: '在校',
    friendliness: '状态待补充',
    vaccine: '一针 2025-11-01；二针 2026-04-01；三针 2026-05-18',
    nextWindow: '加强针约 2027-05-18',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '二橙',
    status: '在校',
    friendliness: '状态待补充',
    vaccine: '一针 2026-03-01；二针 2026-03-01；三针 2026-04-01',
    nextWindow: '—',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '二柑',
    status: '在校',
    friendliness: '状态待补充',
    vaccine: '一针 2026-03-01；二针 2026-03-01；三针 2026-04-01',
    nextWindow: '—',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '渣男',
    status: '在校',
    friendliness: '不怕人',
    vaccine: '未接种',
    nextWindow: '待首针，病后评估',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '2026-05-31 诊断牙龈炎，治疗中。疫苗需等病后评估。',
    source: '在校猫咪名单'
  },
  {
    name: '豆腐脑',
    status: '在校',
    friendliness: '行踪不定',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '2026-05-10',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '脏白',
    status: '在校',
    friendliness: '行踪不定',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '蓝豆',
    status: '在校',
    friendliness: '有点怕人',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '天水',
    status: '在校',
    friendliness: '行踪不定',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '来才',
    status: '在校',
    friendliness: '行踪不定',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '焦炭馒头',
    status: '在校',
    friendliness: '行踪不定',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '小小黑',
    status: '在校',
    friendliness: '行踪不定',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '2026-05-17',
    adopter: '—',
    destination: '学校',
    notes: '2026-05-17 在缘愈绝育/治疗，术后恢复待跟进。',
    source: '在校猫咪名单'
  },
  {
    name: '邪恶橘白',
    status: '在校',
    friendliness: '怕人，尝试抓捕失败',
    vaccine: '未接种',
    nextWindow: '待首针',
    sterilized: '未知',
    adopter: '—',
    destination: '学校',
    notes: '—',
    source: '在校猫咪名单'
  },
  {
    name: '面茶（原新奶牛）',
    status: '已领养',
    friendliness: '—',
    vaccine: '品牌待追溯·一针 2026-05-14（紫薇京和）；二针窗口 6.4~6.11；三针待认领',
    nextWindow: '二针窗口 6.4~6.11',
    sterilized: '待补充',
    adopter: 'meow',
    destination: '西安',
    notes: '2026-05-14 疫苗费用由猫协垫付',
    source: '已领养猫咪名单'
  },
  {
    name: '麻薯',
    status: '已领养',
    friendliness: '不怕人',
    vaccine: '未接种（受伤期评估后未补种）',
    nextWindow: '—',
    sterilized: '待补充',
    adopter: '潇洒不玉玉',
    destination: '广东东莞',
    notes: '曾受伤，仍有猫传腹风险；领养时未补种疫苗。',
    source: '已领养猫咪名单'
  },
  {
    name: '豆花',
    status: '已领养',
    friendliness: '—',
    vaccine: '品牌待追溯·一针 2026-04-29（紫薇京和）；二针待追溯；三针约 2026-05-24',
    nextWindow: '—',
    sterilized: '待补充',
    adopter: '潇洒不玉玉',
    destination: '广东东莞',
    notes: '三针医院或品牌待追溯',
    source: '已领养猫咪名单'
  },
  {
    name: '二头',
    status: '已领养',
    friendliness: '—',
    vaccine: '妙三多·一针 2025-07-27；二针 2025-09-06；三针 2025-09-27（紫薇京和）',
    nextWindow: '—',
    sterilized: '2023 已绝育',
    adopter: '满分猫猫大王的朋友',
    destination: '江苏南京',
    notes: '2026-06-01 领养前体检总体健康，轻微膀胱炎。',
    source: '已领养猫咪名单'
  },
  {
    name: '白介',
    status: '预计领养',
    friendliness: '—',
    vaccine: '品牌待追溯·一针待追溯；二针待追溯；三针窗口 5.26~6.2（紫薇京和）',
    nextWindow: '三针窗口 5.26~6.2',
    sterilized: '待补充',
    adopter: '待补充',
    destination: '上海',
    notes: '预计 2026-06-15 领养',
    source: '已领养猫咪名单'
  },
  {
    name: '小花',
    status: '预计领养',
    friendliness: '—',
    vaccine: '妙三多·三针已完成（具体日期待追溯）',
    nextWindow: '—',
    sterilized: '待补充',
    adopter: '待补充',
    destination: '待补充',
    notes: '预计 2026-06，具体日期待补充',
    source: '已领养猫咪名单'
  },
  {
    name: '大头',
    image: '大头照片_1.jpg',
    status: '预计领养',
    friendliness: '—',
    vaccine: '妙三多·一针 2025-07-27；二针 2025-09-09；三针 2025-10-07（紫薇京和）',
    nextWindow: '—',
    sterilized: '待补充',
    adopter: '待补充',
    destination: '待补充',
    notes: '预计领养，具体日期待补充',
    source: '已领养猫咪名单'
  },
  {
    name: '漂亮橘',
    status: '预计领养',
    friendliness: '—',
    vaccine: '妙三多·一针 2026-05-10；二针 2026-05-31；三针待认领',
    nextWindow: '三针待认领',
    sterilized: '待补充',
    adopter: '待补充',
    destination: '待补充',
    notes: '预计领养，具体日期待补充',
    source: '已领养猫咪名单'
  },
  {
    name: '橙留香',
    status: '预计领养',
    friendliness: '—',
    vaccine: '喵倍护·三针已完成（具体日期待追溯）',
    nextWindow: '—',
    sterilized: '待补充',
    adopter: '待补充',
    destination: '待补充',
    notes: '预计领养，具体日期待补充',
    source: '已领养猫咪名单'
  },
  {
    name: '裤裤',
    status: '预计领养',
    friendliness: '—',
    vaccine: '喵倍护·三针已完成（具体日期待追溯）',
    nextWindow: '加强针认捐人：文耀',
    sterilized: '待补充',
    adopter: '待补充',
    destination: '待补充',
    notes: '预计领养，具体日期待补充',
    source: '已领养猫咪名单'
  },
  {
    name: '深情哥',
    status: '预计领养',
    friendliness: '—',
    vaccine: '喵倍护·三针已完成（具体日期待追溯）；加强针 2026-05-11',
    nextWindow: '—',
    sterilized: '待补充',
    adopter: '待补充',
    destination: '待补充',
    notes: '预计领养，具体日期待补充',
    source: '已领养猫咪名单'
  },
  {
    name: '咖啡',
    status: '已离世',
    friendliness: '—',
    vaccine: '—',
    nextWindow: '—',
    sterilized: '—',
    adopter: '—',
    destination: '—',
    notes: '约 2026-04-30 因猫瘟去世，具体日期待补充。',
    source: '已离世或失踪猫咪名单'
  }
];
